### ISSUE TITLE
error when run

### ISSUE THREAD

**Issue by fukemy** [AdrianKuta/Expandable-RecyclerView#3]
hi, i using your lib with gradle
```

    implementation 'com.github.adriankuta:expandable-recyclerView:1.0.0'
```

gradle sync success, but when press run button i got this error:

```
Execution failed for task ':app:processDevDebugMainManifest'.
> Manifest merger failed with multiple errors, see logs

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.


```
but when remove lib then run gradle, app run normally, can u help?

**Comment by AdrianKuta** [comment]
Hi @fukemy,
Thank you for your question, I will take a look on that

**Comment by AdrianKuta** [comment]
@fukemy 
Could you provide screenshot with error from `Merged Manifest`?
I mean tab in `AndroidManifest.xml` file, the same as in this answer: https://stackoverflow.com/a/42023614/4631935
![image](https://user-images.githubusercontent.com/46381935/131965041-cb8fc1ab-e6b3-4f0f-8eae-3658072549dd.png)

**Comment by fukemy** [comment]
i removed the line 
        tools:replace="android:icon" 
in androidManifest then problem disapear
